"""Quick test: NeuralFoil (PINN) on NACA airfoils generated by our module."""
from __future__ import annotations

import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import neuralfoil as nf
from rc_aircraft_design.aero.airfoil import naca4


def make_selig_coords(code: str, n_points: int = 80) -> np.ndarray:
    """NACA 4-digit -> Selig-format coordinate array (N×2)."""
    x, yu, yl = naca4(code, n_points=n_points)
    # upper TE→LE then lower LE→TE
    return np.column_stack([
        np.concatenate([x[::-1], x[1:]]),
        np.concatenate([yu[::-1], yl[1:]]),
    ])


def run_sweep(code: str, Re: float, alphas: np.ndarray):
    coords = make_selig_coords(code)
    aero = nf.get_aero_from_coordinates(coords, alpha=alphas, Re=Re)
    return aero


# ── Run ──────────────────────────────────────────────────────────────
alphas = np.linspace(-5, 15, 41)
Re = 200_000  # typical RC Reynolds number

foils = ["0012", "2412", "4412", "6412"]
results = {}
for code in foils:
    print(f"Running NeuralFoil on NACA {code}  (Re={Re:.0f}) ...")
    results[code] = run_sweep(code, Re, alphas)

# ── Print table for NACA 2412 ────────────────────────────────────────
print(f"\n{'alpha':>6}  {'CL':>8}  {'CD':>9}  {'CM':>8}")
print("-" * 36)
a2412 = results["2412"]
for i in range(0, len(alphas), 4):
    print(f"{alphas[i]:6.1f}  {a2412['CL'][i]:8.4f}  {a2412['CD'][i]:9.5f}  {a2412['CM'][i]:8.4f}")

# ── Plot ─────────────────────────────────────────────────────────────
fig, axes = plt.subplots(2, 2, figsize=(12, 9))

for code in foils:
    r = results[code]
    axes[0, 0].plot(alphas, r["CL"], label=f"NACA {code}")
    axes[0, 1].plot(alphas, r["CD"], label=f"NACA {code}")
    axes[1, 0].plot(alphas, r["CL"] / r["CD"], label=f"NACA {code}")
    axes[1, 1].plot(r["CD"], r["CL"], label=f"NACA {code}")

axes[0, 0].set(xlabel="α [deg]", ylabel="CL", title="Lift curve (NeuralFoil)")
axes[0, 0].legend(fontsize=8); axes[0, 0].grid(True, alpha=0.3)

axes[0, 1].set(xlabel="α [deg]", ylabel="CD", title="Drag curve")
axes[0, 1].legend(fontsize=8); axes[0, 1].grid(True, alpha=0.3)

axes[1, 0].set(xlabel="α [deg]", ylabel="L/D", title="Lift-to-drag ratio")
axes[1, 0].legend(fontsize=8); axes[1, 0].grid(True, alpha=0.3)

axes[1, 1].set(xlabel="CD", ylabel="CL", title="Drag polar")
axes[1, 1].legend(fontsize=8); axes[1, 1].grid(True, alpha=0.3)

fig.suptitle(f"NeuralFoil (PINN) — Re = {Re:,.0f}", fontsize=14, fontweight="bold")
fig.tight_layout()

from datetime import datetime
run_id = datetime.now().strftime("%Y%m%d_%H%M%S")
out = Path(__file__).resolve().parent.parent / "results" / "examples" / run_id
out.mkdir(parents=True, exist_ok=True)
path = out / "neuralfoil_polars.png"
fig.savefig(path, dpi=150, bbox_inches="tight")
plt.close(fig)
print(f"\nPlot saved → {path}")
